export const VendorParameters = {
    Name: {
        HTMLTag: "input",
        inputType: "text",
        inputName: "name",
        inputLabel: "Name",
        inputPlaceholder: "Name",
        inputRequired: true,
        inputDisabled: false,
        inputReadOnly: false,
    },
    NamePackage: {
        HTMLTag: "input",
        inputType: "text",
        inputName: "namePackage",
        inputLabel: "Name of Package",
        inputPlaceholder: "Name of Package",
        inputRequired: true,
        inputDisabled: false,
        inputReadOnly: false,
    },
    Description: {
        HTMLTag: "textarea",
        inputName: "description",
        inputLabel: "Description",
        inputPlaceholder: "Description",
        inputRequired: true,
        inputDisabled: false,
        inputReadOnly: false,
    },
    Type: {
        HTMLTag: "select",
        inputName: "type",
        inputLabel: "Type",
        inputRequired: true,
        InParameter: {
            Library: {
                optionValue: "Library",
                optionLabel: "Library",
            },
            Project: {
                optionValue: "Project",
                optionLabel: "Project",
            },
            Metapackage: {
                optionValue: "Metapackage",
                optionLabel: "Metapackage",
            },
            ComposerPlugin: {
                optionValue: "ComposerPlugin",
                optionLabel: "ComposerPlugin",
            },
        },
    },
    NameAuthor: {
        HTMLTag: "input",
        inputType: "text",
        inputName: "nameAuthor",
        inputLabel: "Name of Author",
        inputPlaceholder: "Name of Author",
        inputRequired: true,
        inputDisabled: false,
        inputReadOnly: false,
    },
    EmailAuthor: {
        HTMLTag: "input",
        inputType: "email",
        inputName: "emailAuthor",
        inputLabel: "Email of Author",
        inputPlaceholder: "Email of Author",
        inputRequired: true,
        inputDisabled: false,
        inputReadOnly: false,
    },
    Stability: {
        HTMLTag: "select",
        inputName: "stability",
        inputLabel: "Stability",
        inputRequired: true,
        InParameter: {
            Stable: {
                optionValue: "Stable",
                optionLabel: "Stable",
            },
            RC: {
                optionValue: "RC",
                optionLabel: "RC",
            },
            Beta: {
                optionValue: "Beta",
                optionLabel: "Beta",
            },
            Alpha: {
                optionValue: "Alpha",
                optionLabel: "Alpha",
            },
            Dev: {
                optionValue: "Dev",
                optionLabel: "Dev",
            },
        },
    },
    Command: {
        HTMLTag: "input",
        inputType: "text",
        inputName: "command",
        inputLabel: "Command",
        inputPlaceholder: "Command",
        inputRequired: true,
        inputDisabled: false,
        inputReadOnly: false,
    },
    File: {
        HTMLTag: "input",
        inputType: "file",
        inputName: "file",
        inputLabel: "File",
        inputPlaceholder: "File",
        accept: ".php",
    },
    Submit: {
        HTMLTag: "input",
        inputType: "submit",
        inputName: "Submit",
        inputDisabled: false,
    },
};
